spring.application.name=alumnos
server.port=8080

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.svsrbxojghgtbizvsbul
spring.datasource.password=Alozaina.12

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

